import bg1 from "../assets/bg-1.png";
import bg2 from "../assets/bg-2.png";
import bg3 from "../assets/bg-3.png";
import bg4 from "../assets/bg-4.png";
import bg5 from "../assets/bg-5.png";
import bg6 from "../assets/bg-6.png";
import bg7 from "../assets/bg-7.png";
import bg8 from "../assets/bg-8.png";
import bg9 from "../assets/bg-9.png";
import bg10 from "../assets/bg-1.png";
import bg11 from "../assets/bg-2.png";
import bg12 from "../assets/bg-3.png";
import bg13 from "../assets/bg-4.png";
import bg14 from "../assets/bg-5.png";
import bg15 from "../assets/bg-6.png";
import bg16 from "../assets/bg-7.png";
import bg17 from "../assets/bg-8.png";
import bg18 from "../assets/bg-9.png";

const titles = [
    "Real House Luxury Villa",
    "Modern Apartment",
    "Cozy Bungalow",
    "Elegant Mansion",
    "Urban Flat",
    "Country House",
    "Beachfront Villa",
    "Penthouse Suite",
    "Suburban Home",
    "Mountain Cabin",
    "City Loft",
    "Rustic Cottage",
    "Luxury Condo",
    "Downtown Studio",
    "Historic Home",
    "Modern Townhouse",
    "Seaside Retreat",
    "Countryside Villa",
    "Luxury Penthouse",
    "Modern Loft",
    "Cozy Cottage",
    "Elegant Villa",
    "Urban Studio",
    "Country Villa",
    "Beach House",
    "Penthouse Apartment",
    "Suburban Villa",
    "Mountain House",
    "City Apartment",
    "Rustic Villa",
    "Luxury Apartment",
    "Downtown Loft",
    "Historic Villa",
    "Modern Apartment",
    "Seaside Villa",
    "Countryside House",
];

const locations = [
    "Victoria Island, Lagos",
    "Lekki, Lagos",
    "Ikeja, Lagos",
    "Surulere, Lagos",
    "Yaba, Lagos",
    "Ikoyi, Lagos",
    "Ajah, Lagos",
    "Epe, Lagos",
    "Badagry, Lagos",
    "Ibadan, Oyo",
    "Abeokuta, Ogun",
    "Port Harcourt, Rivers",
    "Enugu, Enugu",
    "Abuja, FCT",
    "Kano, Kano",
    "Kaduna, Kaduna",
    "Jos, Plateau",
    "Benin, Edo",
    "Warri, Delta",
    "Calabar, Cross River",
    "Uyo, Akwa Ibom",
    "Owerri, Imo",
    "Onitsha, Anambra",
    "Asaba, Delta",
    "Makurdi, Benue",
    "Minna, Niger",
    "Sokoto, Sokoto",
    "Zaria, Kaduna",
    "Gombe, Gombe",
    "Bauchi, Bauchi",
    "Maiduguri, Borno",
    "Lokoja, Kogi",
    "Ado Ekiti, Ekiti",
    "Akure, Ondo",
    "Osogbo, Osun",
];

const bedrooms = [5, 3, 4, 6, 2, 3, 4, 5, 3, 4, 2, 3, 5, 1, 4, 3, 6, 2, 4, 3, 5, 2, 3, 4, 5, 3, 4, 2, 3, 5, 1, 4, 3, 6, 2];
const bathrooms = [3, 2, 2, 4, 1, 2, 3, 3, 2, 3, 1, 2, 4, 1, 3, 2, 4, 1, 3, 2, 4, 1, 2, 3, 3, 2, 3, 1, 2, 4, 1, 3, 2, 4, 1];
const prices = [
    "N 4,000,000/1 Year",
    "N 2,500,000/1 Year",
    "N 3,000,000/1 Year",
    "N 5,000,000/1 Year",
    "N 1,500,000/1 Year",
    "N 2,800,000/1 Year",
    "N 3,500,000/1 Year",
    "N 4,200,000/1 Year",
    "N 2,700,000/1 Year",
    "N 3,800,000/1 Year",
    "N 1,200,000/1 Year",
    "N 2,600,000/1 Year",
    "N 4,500,000/1 Year",
    "N 1,000,000/1 Year",
    "N 3,200,000/1 Year",
    "N 2,400,000/1 Year",
    "N 5,500,000/1 Year",
    "N 1,800,000/1 Year",
    "N 4,200,000/1 Year",
    "N 2,700,000/1 Year",
    "N 3,800,000/1 Year",
    "N 1,200,000/1 Year",
    "N 2,600,000/1 Year",
    "N 4,500,000/1 Year",
    "N 1,000,000/1 Year",
    "N 3,200,000/1 Year",
    "N 2,400,000/1 Year",
    "N 5,500,000/1 Year",
    "N 1,800,000/1 Year",
    "N 4,000,000/1 Year",
    "N 2,500,000/1 Year",
    "N 3,000,000/1 Year",
    "N 5,000,000/1 Year",
    "N 1,500,000/1 Year",
    "N 2,800,000/1 Year",
];

const shuffleArray = (array) => {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
};

export const dummyData = shuffleArray([
    {
        id: 1,
        imageUrl: bg1,
        title: titles[0],
        location: locations[0],
        bedrooms: bedrooms[0],
        bathrooms: bathrooms[0],
        price: prices[0],
        featured: true,
        forSale: true,
    },
    {
        id: 2,
        imageUrl: bg2,
        title: titles[1],
        location: locations[1],
        bedrooms: bedrooms[1],
        bathrooms: bathrooms[1],
        price: prices[1],
        featured: true,
        forSale: true,
    },
    {
        id: 3,
        imageUrl: bg3,
        title: titles[2],
        location: locations[2],
        bedrooms: bedrooms[2],
        bathrooms: bathrooms[2],
        price: prices[2],
        featured: true,
        forSale: true,
    },
    {
        id: 4,
        imageUrl: bg4,
        title: titles[3],
        location: locations[3],
        bedrooms: bedrooms[3],
        bathrooms: bathrooms[3],
        price: prices[3],
        featured: true,
        forSale: true,
    },
    {
        id: 5,
        imageUrl: bg5,
        title: titles[4],
        location: locations[4],
        bedrooms: bedrooms[4],
        bathrooms: bathrooms[4],
        price: prices[4],
        featured: true,
        forSale: true,
    },
    {
        id: 6,
        imageUrl: bg6,
        title: titles[5],
        location: locations[5],
        bedrooms: bedrooms[5],
        bathrooms: bathrooms[5],
        price: prices[5],
        featured: true,
        forSale: true,
    },
    {
        id: 7,
        imageUrl: bg7,
        title: titles[6],
        location: locations[6],
        bedrooms: bedrooms[6],
        bathrooms: bathrooms[6],
        price: prices[6],
        featured: true,
        forSale: true,
    },
    {
        id: 8,
        imageUrl: bg8,
        title: titles[7],
        location: locations[7],
        bedrooms: bedrooms[7],
        bathrooms: bathrooms[7],
        price: prices[7],
        featured: true,
        forSale: true,
    },
    {
        id: 9,
        imageUrl: bg9,
        title: titles[8],
        location: locations[8],
        bedrooms: bedrooms[8],
        bathrooms: bathrooms[8],
        price: prices[8],
        featured: true,
        forSale: true,
    },
    {
        id: 10,
        imageUrl: bg10,
        title: titles[9],
        location: locations[9],
        bedrooms: bedrooms[9],
        bathrooms: bathrooms[9],
        price: prices[9],
        featured: true,
        forSale: true,
    },
    {
        id: 11,
        imageUrl: bg11,
        title: titles[10],
        location: locations[10],
        bedrooms: bedrooms[10],
        bathrooms: bathrooms[10],
        price: prices[10],
        featured: true,
        forSale: true,
    },
    {
        id: 12,
        imageUrl: bg12,
        title: titles[11],
        location: locations[11],
        bedrooms: bedrooms[11],
        bathrooms: bathrooms[11],
        price: prices[11],
        featured: true,
        forSale: true,
    },
    {
        id: 13,
        imageUrl: bg13,
        title: titles[12],
        location: locations[12],
        bedrooms: bedrooms[12],
        bathrooms: bathrooms[12],
        price: prices[12],
        featured: true,
        forSale: true,
    },
    {
        id: 14,
        imageUrl: bg14,
        title: titles[13],
        location: locations[13],
        bedrooms: bedrooms[13],
        bathrooms: bathrooms[13],
        price: prices[13],
        featured: true,
        forSale: true,
    },
    {
        id: 15,
        imageUrl: bg15,
        title: titles[14],
        location: locations[14],
        bedrooms: bedrooms[14],
        bathrooms: bathrooms[14],
        price: prices[14],
        featured: true,
        forSale: true,
    },
    {
        id: 16,
        imageUrl: bg16,
        title: titles[15],
        location: locations[15],
        bedrooms: bedrooms[15],
        bathrooms: bathrooms[15],
        price: prices[15],
        featured: true,
        forSale: true,
    },
    {
        id: 17,
        imageUrl: bg17,
        title: titles[16],
        location: locations[16],
        bedrooms: bedrooms[16],
        bathrooms: bathrooms[16],
        price: prices[16],
        featured: true,
        forSale: true,
    },
    {
        id: 18,
        imageUrl: bg18,
        title: titles[17],
        location: locations[17],
        bedrooms: bedrooms[17],
        bathrooms: bathrooms[17],
        price: prices[17],
        featured: true,
        forSale: true,
    },
    {
        id: 19,
        imageUrl: bg1,
        title: titles[18],
        location: locations[18],
        bedrooms: bedrooms[18],
        bathrooms: bathrooms[18],
        price: prices[18],
        featured: true,
        forSale: true,
    },
    {
        id: 20,
        imageUrl: bg2,
        title: titles[19],
        location: locations[19],
        bedrooms: bedrooms[19],
        bathrooms: bathrooms[19],
        price: prices[19],
        featured: true,
        forSale: true,
    },
    {
        id: 21,
        imageUrl: bg3,
        title: titles[20],
        location: locations[20],
        bedrooms: bedrooms[20],
        bathrooms: bathrooms[20],
        price: prices[20],
        featured: true,
        forSale: true,
    },
    {
        id: 22,
        imageUrl: bg4,
        title: titles[21],
        location: locations[21],
        bedrooms: bedrooms[21],
        bathrooms: bathrooms[21],
        price: prices[21],
        featured: true,
        forSale: true,
    },
    {
        id: 23,
        imageUrl: bg5,
        title: titles[22],
        location: locations[22],
        bedrooms: bedrooms[22],
        bathrooms: bathrooms[22],
        price: prices[22],
        featured: true,
        forSale: true,
    },
    {
        id: 24,
        imageUrl: bg6,
        title: titles[23],
        location: locations[23],
        bedrooms: bedrooms[23],
        bathrooms: bathrooms[23],
        price: prices[23],
        featured: true,
        forSale: true,
    },
    {
        id: 25,
        imageUrl: bg7,
        title: titles[24],
        location: locations[24],
        bedrooms: bedrooms[24],
        bathrooms: bathrooms[24],
        price: prices[24],
        featured: true,
        forSale: true,
    },
    {
        id: 26,
        imageUrl: bg8,
        title: titles[25],
        location: locations[25],
        bedrooms: bedrooms[25],
        bathrooms: bathrooms[25],
        price: prices[25],
        featured: true,
        forSale: true,
    },
    {
        id: 27,
        imageUrl: bg9,
        title: titles[26],
        location: locations[26],
        bedrooms: bedrooms[26],
        bathrooms: bathrooms[26],
        price: prices[26],
        featured: true,
        forSale: true,
    },
    {
        id: 28,
        imageUrl: bg10,
        title: titles[27],
        location: locations[27],
        bedrooms: bedrooms[27],
        bathrooms: bathrooms[27],
        price: prices[27],
        featured: true,
        forSale: true,
    },
    {
        id: 29,
        imageUrl: bg11,
        title: titles[28],
        location: locations[28],
        bedrooms: bedrooms[28],
        bathrooms: bathrooms[28],
        price: prices[28],
        featured: true,
        forSale: true,
    },
    {
        id: 30,
        imageUrl: bg12,
        title: titles[29],
        location: locations[29],
        bedrooms: bedrooms[29],
        bathrooms: bathrooms[29],
        price: prices[29],
        featured: true,
        forSale: true,
    },
    {
        id: 31,
        imageUrl: bg13,
        title: titles[30],
        location: locations[30],
        bedrooms: bedrooms[30],
        bathrooms: bathrooms[30],
        price: prices[30],
        featured: true,
        forSale: true,
    },
    {
        id: 32,
        imageUrl: bg14,
        title: titles[31],
        location: locations[31],
        bedrooms: bedrooms[31],
        bathrooms: bathrooms[31],
        price: prices[31],
        featured: true,
        forSale: true,
    },
    {
        id: 33,
        imageUrl: bg15,
        title: titles[32],
        location: locations[32],
        bedrooms: bedrooms[32],
        bathrooms: bathrooms[32],
        price: prices[32],
        featured: true,
        forSale: true,
    },
    {
        id: 34,
        imageUrl: bg16,
        title: titles[33],
        location: locations[33],
        bedrooms: bedrooms[33],
        bathrooms: bathrooms[33],
        price: prices[33],
        featured: true,
        forSale: true,
    },
    {
        id: 35,
        imageUrl: bg17,
        title: titles[34],
        location: locations[34],
        bedrooms: bedrooms[34],
        bathrooms: bathrooms[34],
        price: prices[34],
        featured: true,
        forSale: true,
    },
    {
        id: 36,
        imageUrl: bg18,
        title: titles[35],
        location: locations[35],
        bedrooms: bedrooms[35],
        bathrooms: bathrooms[35],
        price: prices[35],
        featured: true,
        forSale: true,
    },
]);
